spring.application.name=ams
spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.messages.basename=messages

spring.datasource.url=jdbc:postgresql://192.168.1.114:5432/AMS
spring.datasource.username=postgres
spring.datasource.password=ams
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

# Maximum size of a single file
spring.servlet.multipart.max-file-size=50MB

# Maximum request size (all files combined)
spring.servlet.multipart.max-request-size=200MB

# Maximum number of files per request (Tomcat-specific)
spring.servlet.multipart.file-size-threshold=0

# Session timeout in seconds (3600 seconds = 1 hour)
server.servlet.session.timeout=3600s